development:
  adapter: mysql2
  database: symphony_podcast_development
  username:
  password:
  host: localhost
  port: 3306
  encoding: utf8

test:
  adapter: mysql2
  database: symphony_podcast_test
  username:
  password:
  host: localhost
  port: 3306
  encoding: utf8

production:
  adapter: mysql2
  database: symphony_podcast_production
  username:
  password:
  host: localhost
  encoding: utf8
  timeout: 5000
  pool: 5
  socket: /tmp/mysql.sock

#CLEARDB_DATABASE_URL: mysql2://b71f37ddb63bca:48318436@us-cdbr-iron-east-02.cleardb.net/heroku_7656043fdaf46ed?reconnect=true